### ISSUE TITLE
Whats up! 

### ISSUE THREAD

**Issue by moesaid** [sunarya-thito/shadcn_flutter#1]
Hey! @sunarya-thito !

First off, major props on your package – even in its early stage, I'm already loving the cool vibes and your take on UI abstraction. It's got me daydreaming about all the awesome features it could have. Fantastic job, and a big thank you for sharing it with us!

Now, as I dig into the package, I noticed the docs are still in the making (totally get it, no rush). Quick friendly questions for you:

- Is the package dependent on any external dependencies, or is it self-contained? 
- Regarding routes and state management, is the package opinionated about using something specific, or is it agnostic, focusing solely on UI?
- Do you have any exciting plans or features on the roadmap for future releases of the package?
- Noticed the focus is intended for web, any plans to have the rest of the platforms in mind ?

**Comment by sunarya-thito** [comment]
Hello,
Thank you for your interest in this project!
- The package depends on some packages which you can check at pubspec.yml, I don't know what you mean about self-contained but it might conflict if you have the same dependency with a different version iirc
- You can use any route or state management, this package only provides sets of widgets, think of it like material or cupertino as a package
- There are a lot of widgets I'm planning to implement, such as:
  - https://sonner.emilkowal.ski/
  - https://www.embla-carousel.com/examples/predefined/
  - https://vaul.emilkowal.ski/
- It's optimized for desktop apps and web apps, but not mobile apps since it doesn't have mobile-exclusive widgets (app bar, bottom nav bar, etc), i can probably add it but it's not gonna be my priority for now.
