### ISSUE TITLE
Carousel need to onIndexChange function.

### ISSUE THREAD

**Issue by nhtberk** [sunarya-thito/shadcn_flutter#12]
It will be great feature for carousel because when i use map and carousel, i want to see which carousel index to show in map.

**Comment by sunarya-thito** [comment]
I'll see what I can do, this should be easy to implement, but for now, you can use CarouselController to listen to index changes, just round the CarouselController value to int (because its a double). You can also use AnimatedBuilder so you don't have to update the entire widget and you don't have to register and unregister the listener on widget life cycle changes.
I might publish the next version with this additional parameter a bit late.
