### ISSUE TITLE
Styling Drawer

### ISSUE THREAD

**Issue by goottime** [sunarya-thito/shadcn_flutter#40]
I noticed several problems with Drawer:
- Apparently due to scaling, the drag handle has also increased and now looks too big. I would like to see something in the style of [Material 3](https://m3.material.io/components/bottom-sheets/overview)\. I would also like to see the ability to disable drag handle.
![image](https://github.com/user-attachments/assets/3149b6d8-a603-494f-b799-148ac20597e0)
- Border radius of Drawer does not obey the value specified in the theme. I would also add the ability to configure this when creating the Drawer.
- In the [documentation for Drawer](https://sunarya-thito.github.io/shadcn_flutter/#/components/drawer) there was a transformBackdrop value, but now there is no such parameter. How can you use it now?
- When using edge to edge mode, Drawer has no padding for save area. I suggest adding useSaveArea or something similar. Probably this parameter should also be added to Sheet.

**Comment by sunarya-thito** [comment]
transformBackdrop is used internally to differentiate how a sheet and a drawer should affect the backdrop because behind the stage, both sheet and a drawer are just the same thing sitting in the same overlay layer but have different container shapes and effects to the backdrop, it was probably accidentally put into `openDrawer` method.

**Comment by sunarya-thito** [comment]
I readded back the option, should make you able to customize it more
